accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/detail/', views.user_detail, name = 'detail'),
    path('<int:pk>/detail/update/', views.user_update, name = 'update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('delete/', views.delete, name='delete'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('rank/', views.rank, name='rank'),
    path('movie_list/', views.movie_list, name="movie_list"),
    path('movie_list/search/', views.search, name='search'),
    path('review_list/', views.review_list, name="review_list"),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('recommend/', views.recommend, name='recommend'),
    path('<int:movie_pk>/create/', views.review_create, name = 'review_create'),
    path('<int:movie_pk>/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/<int:review_pk>/dislike/', views.review_dislike, name='review_dislike'),
    path('<int:movie_pk>/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('comment/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('comment/<int:comment_pk>/dislike/', views.comment_dislike, name='comment_dislike'),
    path('<int:movie_pk>/<int:review_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/reply_create/', views.reply_create, name='reply_create'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/<int:reply_pk>/reply_delete/', views.reply_delete, name='reply_delete'),
    path('reply/<int:reply_pk>/like/', views.reply_like, name='reply_like'),
    path('reply/<int:reply_pk>/dislike/', views.reply_dislike, name='reply_dislike'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.name}'


class RepNationNm(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.name}'


class Movie(models.Model):
    movieNm = models.CharField(max_length=100)
    movieNmEn = models.CharField(max_length=100)
    openDt = models.DateField()
    vote_count = models.IntegerField(default=0)
    vote_tot = models.IntegerField(default=0)
    vote_average = models.FloatField(default=0)
    watchGradeNm = models.IntegerField()
    overview = models.TextField()
    repNationNm = models.ManyToManyField(RepNationNm,
                            related_name='repNationNm_movie')
    poster_path = models.CharField(max_length=100)
    backdrop_path1 = models.CharField(max_length=100)
    backdrop_path2 = models.CharField(max_length=100)
    backdrop_path3 = models.CharField(max_length=100)
    genres = models.ManyToManyField(Genre,
                            related_name='genre_movie')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_movies')

    def __str__(self):
        return f'{self.movieNm}'


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie,
                             on_delete=models.CASCADE)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    hit = models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_reviews')
    user_hit_time = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='hit_time_reviews')


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_comments')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_comments')


class Reply(models.Model):
    content = models.TextField()
    comment = models.ForeignKey(Comment,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_reply')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_reply')


class Moviehistory(models.Model):
    movie = models.ForeignKey(Movie,
                             on_delete=models.CASCADE)

class Reviewhistory(models.Model):
    review = models.ForeignKey(Review,
                             on_delete=models.CASCADE)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review, Comment, Reply, Moviehistory, Reviewhistory
from .forms import ReviewForm, CommentForm, ReplyForm, MoviehistoryForm, ReviewhistoryForm
from accounts.forms import UserhistoryForm, UservisitedreviewForm
from accounts.models import Userhistory, Uservisitedreview, User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
import random
import time

# Create your views here.
def index(request):
    user = request.user
    # if user.is_authenticated and user.adult:
    movies = Movie.objects.all()
    # else:
    #     movies = Movie.objects.filter(adult=False)

    paginator = Paginator(movies, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    recommend_recently = Movie.objects.order_by('-openDt')[:10]
    recommend_rank = Movie.objects.order_by('-vote_average')[:10]
    # recommend_num_of_reviews = Movie.objects.order_by('-.review.count()')
    live_movie_history = Moviehistory.objects.all()
    live_movie_dict = {}
    for history in live_movie_history:
        if history.movie in live_movie_dict:
            live_movie_dict[history.movie] += 1
        else:
            live_movie_dict[history.movie] = 1
    live_movie_list = []
    for key in live_movie_dict:
        live_movie_list.append((live_movie_dict[key], key))
    live_movie_list.sort(reverse=True, key = lambda x : x[0])

    live_movies = []
    min_num = min(10, len(live_movie_list))
    for i in range(min_num):
        live_movies.append(live_movie_list[i][1])


    live_review_history = Reviewhistory.objects.all()
    live_review_dict = {}
    for history in live_review_history:
        if history.review in live_review_dict:
            live_review_dict[history.review] += 1
        else:
            live_review_dict[history.review] = 1
    live_review_list = []
    for key in live_review_dict:
        live_review_list.append((live_review_dict[key], key))
    live_review_list.sort(reverse=True, key = lambda x : x[0])

    live_reviews = []
    min_num = min(5, len(live_review_list))
    for i in range(min_num):
        live_reviews.append(live_review_list[i][1])


    users = User.objects.all()
    users_data = []
    for u in users:
        if not u.is_superuser:
            users_data.append((Review.objects.filter(user=u).count(), Comment.objects.filter(user=u).count(), u))
    users_data.sort(reverse=True, key = lambda x : (x[0], x[1]))

    best_users = []
    min_val = min(5, len(users_data))
    for i in range(min_val):
        best_users.append(users_data[i][2])


    manyReviewsList = []
    for movie in movies:
        manyReviewsList.append((movie.review_set.count(), movie))
    manyReviewsList.sort(reverse=True, key = lambda x: x[0])
    manyReviewsMovies = []

    for i in range(10):
        manyReviewsMovies.append(manyReviewsList[i][1])



    context ={
        'movies':movies,
        'page_obj': page_obj,
        'recommend_recently': recommend_recently,
        'recommend_rank': recommend_rank,
        'live_movies': live_movies,
        'live_reviews': live_reviews,
        'best_users':best_users,
        'manyReviewsMovies':manyReviewsMovies
    }
    return render(request, 'movies/index.html', context)


def movie_list(request):
    user = request.user
    # if user.is_authenticated and user.adult:
    movies = Movie.objects.order_by('-pk')
    # else:
    #     movies = Movie.objects.filter(adult=False)

    paginator = Paginator(movies, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context ={
        'movies':movies,
        'page_obj': page_obj,
    }
    return render(request, 'movies/movie_list.html', context)


def search(request):
    search = request.GET.get('search')
    movies = Movie.objects.filter(movieNm__contains=search).order_by('-pk')
    paginator = Paginator(movies, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'page_obj': page_obj,
    }
    return render(request, 'movies/movie_list.html', context)


def rank(request):
    users_with_admin = User.objects.all()
    users = []
    for user in users_with_admin:
        if not user.is_superuser:
            users.append(user)

    movies = Movie.objects.all()

    manyLikedMoviess = []
    for movie in movies:
        manyLikedMoviess.append((movie.like_users.count(), movie))
    manyLikedMoviess.sort(reverse=True, key = lambda x : x[0])
    manyLikedMovies = []
    for movie in manyLikedMoviess[:10]:
        manyLikedMovies.append(movie[1])


    reviews = Review.objects.all()
    manyLikedReviewss = []
    for review in reviews:
        manyLikedReviewss.append((review.like_users.count(), review))
    manyLikedReviewss.sort(reverse=True, key = lambda x : x[0])
    manyLikedReviews = []
    for review in manyLikedReviewss[:10]:
        manyLikedReviews.append(review[1])


    manyHitsReviews = []
    manyHitsReviews_list = reviews.order_by('-hit')
    for review in manyHitsReviews_list[:10]:
        manyHitsReviews.append(review)

    manyCommentsReviews_list = []
    for review in reviews:
        manyCommentsReviews_list.append((review.comment_set.count(), review))
    manyCommentsReviews_list.sort(reverse=True, key = lambda x : x[0])
    manyCommentsReviews = []
    for review in manyCommentsReviews_list[:10]:
        manyCommentsReviews.append(review[1])


    live_movie_history = Moviehistory.objects.all()
    live_movie_dict = {}
    for history in live_movie_history:
        if history.movie in live_movie_dict:
            live_movie_dict[history.movie] += 1
        else:
            live_movie_dict[history.movie] = 1
    live_movie_list = []
    for key in live_movie_dict:
        live_movie_list.append((live_movie_dict[key], key))
    live_movie_list.sort(reverse=True, key = lambda x : x[0])

    live_movies = []
    min_num = min(10, len(live_movie_list))
    for i in range(min_num):
        live_movies.append(live_movie_list[i][1])


    live_review_history = Reviewhistory.objects.all()
    live_review_dict = {}
    for history in live_review_history:
        if history.review in live_review_dict:
            live_review_dict[history.review] += 1
        else:
            live_review_dict[history.review] = 1
    live_review_list = []
    for key in live_review_dict:
        live_review_list.append((live_review_dict[key], key))
    live_review_list.sort(reverse=True, key = lambda x : x[0])

    live_reviews = []
    min_num = min(10, len(live_review_list))
    for i in range(min_num):
        live_reviews.append(live_review_list[i][1])


    users_list = User.objects.all()
    users = []
    for u in users_list:
        if not u.is_superuser:
            users.append((u, Review.objects.filter(user=u).count(), Comment.objects.filter(user=u).count()))
    users.sort(reverse=True, key = lambda x : (x[1], x[2]))

    users_rank = []
    for u in users[:10]:
        users_rank.append(u[0])


    context = {
        'manyLikedMovies':manyLikedMovies,
        'manyLikedReviews':manyLikedReviews,
        'manyHitsReviews':manyHitsReviews,
        'manyCommentsReviews':manyCommentsReviews,
        'live_movies':live_movies,
        'live_reviews':live_reviews,
        'users_rank':users_rank,

    }
    return render(request, 'movies/rank.html', context)


def review_list(request):
    user = request.user
    reviews = Review.objects.order_by('-created_at')

    paginator = Paginator(reviews, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context ={
        'reviews':reviews,
        'page_obj': page_obj,
    }
    return render(request, 'movies/review_list.html', context)


def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    tot_liked = movie.like_users.all().count
    male_liked = movie.like_users.all().filter(sex='남').count()
    female_liked = movie.like_users.all().filter(sex='여').count()
    liked_50 = movie.like_users.all().filter(age__gte=49).count()
    liked_40 = movie.like_users.all().filter(age__gte=39).filter(age__lt=49).count()
    liked_30 = movie.like_users.all().filter(age__gte=29).filter(age__lt=39).count()
    liked_20 = movie.like_users.all().filter(age__gte=19).filter(age__lt=29).count()
    liked_10 = movie.like_users.all().filter(age__lt=19).count()

    recommend_movies = []
    target_genre = []

    for genre in movie.genres.all():
        target_genre.append(genre.name)

    stop = 0
    movies = Movie.objects.all()
    while len(recommend_movies) < 3 and stop < 100:
        stop += 1
        sample = random.choice(movies)
        if sample in recommend_movies:
            continue
        if sample == movie:
            continue

        for genre in sample.genres.all():
            if genre.name in target_genre:
                recommend_movies.append(sample)
                break
    # Review.objects.all()
    # male_liked = movie.like_users.all().filter(sex='남').count()

    if request.user.is_authenticated:
        if Userhistory.objects.all().filter(user=request.user).count() >= 50:
            Userhistory.objects.all().filter(user=request.user).order_by('pk')[0].delete()
        form = UserhistoryForm(request.POST)
        userhistory = form.save(commit=False)
        userhistory.user = request.user
        userhistory.movie_pk = movie_pk
        userhistory.save()


    reviews = Review.objects.order_by('-pk').filter(movie=movie)
    paginator = Paginator(reviews, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if Moviehistory.objects.all().count() >= 1000:
        Moviehistory.objects.all().order_by('pk')[0].delete()

movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}
{% block css %}
<link rel="stylesheet" href="/static/css/modal.css">
{% endblock %}
{% block body %}

<style>
  .fa-info-circle:hover {
    color: gold;
  }
</style>



<div class='container justify-content-center'>
  <h2 style="text-align:center;">영화 목록</h2>
  <hr width="150px">
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">영화 제목</th>
      <th scope="col">장르</th>
      <th scope="col">평점</th>
      <th scope="col">추천 수</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in page_obj %}
    <!--Modal-->
    <div class="modal fade" id="modal-{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="modal1Label" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="modal1Label">{{movie.movieNm}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                {% if movie.backdrop_path == '' %}
                  <p>이미지가 없습니다.</p>
                {% else %}
                  <img src="{{ movie.poster_path }}" alt="" style="width: 100%">
                {% endif %}
                  <div class="description">
                  <p class="img__description">{{ movie.overview }}</p>
              </div>
            </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
          </div>
        </div>
    </div>

    <tr>
      <td><a href="{% url 'movies:movie_detail' movie.pk %}" class="text-dark">{{movie.movieNm}} </a><i class="fas fa-info-circle" data-toggle="modal" data-target="#modal-{{ movie.id }}"></i></th>
      <td>  {% for genre in movie.genres.all %}
      <span class="badge badge-info">{{ genre.name }} </span>
            {% endfor %}</td>
      <td>{{movie.vote_average}}</td>
      <td>{{movie.like_users.count}}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<div class="pagination justify-content-center">
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
</div>


{% endblock %}

movies/templates/movies/rank.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block body %}
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 style="text-align:center;"><i class="fas fa-award"></i> 랭킹 <i class="fas fa-award"></i></h2>
          <hr width="100px">
            <ul class="nav nav-tabs justify-content-center">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#liked">좋아요 Top10</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#hits">조회 수 Top10</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#comments">댓글 수 Top10</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#live">실시간 Top10</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#user_rank">유저 Top10</a>
              </li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane fade show active" id="liked">
              <p>
                <table class="table table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">랭킹</th>
                      <th scope="col">제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">평점</th>
                      <th scope="col">좋아요</th>
                      <th scope="col">조회수</th>
                    </tr>
                  </thead>
                  {% for review in manyLikedReviews %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
                      {% if review.comment_set.all.count > 0 %}
                        <span>({{ review.comment_set.all.count }})</span>
                      {% endif %}
                      </a></th>
                      <td><a href="{% url 'accounts:detail' review.user.pk %}" class="text-dark">{{ review.user.nickname }}</a></td>
                      <td>{{ review.rank }}</td>
                      <td>{{review.like_users.count}}</td>
                      <td>{{ review.hit }}</td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
              </div>
              <div class="tab-pane fade" id="hits">
                <p>
                <table class="table table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">랭킹</th>
                      <th scope="col">제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">평점</th>
                      <th scope="col">좋아요</th>
                      <th scope="col">조회수</th>
                    </tr>
                  </thead>
                  {% for review in manyHitsReviews %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
                      {% if review.comment_set.all.count > 0 %}
                        <span>({{ review.comment_set.all.count }})</span>
                      {% endif %}
                      </a></th>
                      <td><a href="{% url 'accounts:detail' review.user.pk %}" class="text-dark">{{ review.user.nickname }}</a></td>
                      <td>{{ review.rank }}</td>
                      <td>{{review.like_users.count}}</td>
                      <td>{{ review.hit }}</td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
              </div>
              <div class="tab-pane fade" id="comments">
                <p>
                <table class="table table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">랭킹</th>
                      <th scope="col">제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">평점</th>
                      <th scope="col">좋아요</th>
                      <th scope="col">조회수</th>
                    </tr>
                  </thead>
                  {% for review in manyCommentsReviews %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
                      {% if review.comment_set.all.count > 0 %}
                        <span>({{ review.comment_set.all.count }})</span>
                      {% endif %}
                      </a></th>
                      <td><a href="{% url 'accounts:detail' review.user.pk %}" class="text-dark">{{ review.user.nickname }}</a></td>
                      <td>{{ review.rank }}</td>
                      <td>{{review.like_users.count}}</td>
                      <td>{{ review.hit }}</td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
              </div>
              <div class="tab-pane fade" id="live">
                <p>
                <table class="table table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">랭킹</th>
                      <th scope="col">제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">평점</th>
                      <th scope="col">좋아요</th>
                      <th scope="col">조회수</th>
                    </tr>
                  </thead>
                  {% for review in manyHitsReviews %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
                      {% if review.comment_set.all.count > 0 %}
                        <span>({{ review.comment_set.all.count }})</span>
                      {% endif %}
                      </a></th>
                      <td><a href="{% url 'accounts:detail' review.user.pk %}" class="text-dark">{{ review.user.nickname }}</a></td>
                      <td>{{ review.rank }}</td>
                      <td>{{review.like_users.count}}</td>
                      <td>{{ review.hit }}</td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
              </div>
              <div class="tab-pane fade" id="user_rank">
                <p>
                <table class="table table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">랭킹</th>
                      <th scope="col">닉네임</th>
                      <th scope="col">게시글 수</th>
                      <th scope="col">댓글 수</th>
                    </tr>
                  </thead>
                  {% for u in users_rank %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'accounts:detail' u.pk %}" class="text-dark">{{ u.nickname }}</a></td>
                      <td>{{ u.review_set.count }}</td>
                      <td>{{ u.comment_set.count}} </td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
              </div>
            </div>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

movies/templates/movies/review_list.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block body %}

<style>
  .show_img:hover {
    border: 1px solid;
  }
</style>

{% if flag %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>WARNING!</strong> 성인인증이 필요한 리뷰입니다.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<div class='container justify-content-center'>
  <h2 style="text-align:center;">리뷰 목록</h2>
  <hr width="150px">
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Num</th>
      <th scope="col">제목</th>
      <th scope="col">영화제목</th>
      <th scope="col">작성자</th>
      <th scope="col">평점</th>
      <th scope="col">좋아요</th>
      <th scope="col">조회수</th>
    </tr>
  </thead>
  <tbody>
    {% for review in page_obj %}

    <tr>
      <th scope="row">{{review.pk}}</th>
      {% if request.user.is_authenticated %}
        {% if review.movie.watchGradeNm == 19 %}
          {% if request.user.age < 19 %}
            <td><a class="text-dark" data-toggle="modal" data-target="#exampleModal">
              {{review.title}}
          {% else %}
          <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
          {% endif %}
        {% else %}
        <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
        {% endif %}
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    성인영화의 리뷰는 열람이 불가능합니다.
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                  </div>
                </div>
              </div>
            </div>
      {% else %}
      <td><a href="{% url 'movies:review_detail' review.movie.pk review.pk %}" class="text-dark">{{review.title}}
      {% endif %}


      {% if review.comment_set.all.count > 0 %}
        <span>({{ review.comment_set.all.count }})</span>
      {% endif %}
      </a></td>
      <td><a href="{% url 'movies:movie_detail' review.movie.pk %}" class="text-dark">{{ review.movie.movieNm }}</a></td>
      <td><a href="{% url 'accounts:detail' review.user.pk %}" class="text-dark">{{ review.user.nickname }}</a></td>
      <td>{{ review.rank }}</td>
      <td>{{review.like_users.count}}</td>
      <td>{{ review.hit }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<div class="pagination justify-content-center">
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
</div>


{% endblock %}