accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/detail/', views.user_detail, name = 'detail'),
    path('<int:pk>/detail/update/', views.user_update, name = 'update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('delete/', views.delete, name='delete'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('rank/', views.rank, name='rank'),
    path('movie_list/', views.movie_list, name="movie_list"),
    path('movie_list/search/', views.search, name='search'),
    path('review_list/', views.review_list, name="review_list"),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('recommend/', views.recommend, name='recommend'),
    path('<int:movie_pk>/create/', views.review_create, name = 'review_create'),
    path('<int:movie_pk>/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/<int:review_pk>/dislike/', views.review_dislike, name='review_dislike'),
    path('<int:movie_pk>/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('comment/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('comment/<int:comment_pk>/dislike/', views.comment_dislike, name='comment_dislike'),
    path('<int:movie_pk>/<int:review_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/reply_create/', views.reply_create, name='reply_create'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/<int:reply_pk>/reply_delete/', views.reply_delete, name='reply_delete'),
    path('reply/<int:reply_pk>/like/', views.reply_like, name='reply_like'),
    path('reply/<int:reply_pk>/dislike/', views.reply_dislike, name='reply_dislike'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from movies.models import Review
# Create your models here.


class Uservisitedreview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    review = models.ForeignKey(Review,
                             on_delete=models.CASCADE)
    visited_time = models.IntegerField()


class Userhistory(models.Model):
    movie_pk = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)


class User(AbstractUser):
    age = models.IntegerField(default=0)
    rrn = models.IntegerField(default=0)
    sex = models.CharField(max_length=10, default='남')
    followings = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='follower'
        )
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='following'
        )
    nickname = models.CharField(max_length=20)

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.name}'


class RepNationNm(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.name}'


class Movie(models.Model):
    movieNm = models.CharField(max_length=100)
    movieNmEn = models.CharField(max_length=100)
    openDt = models.DateField()
    vote_count = models.IntegerField(default=0)
    vote_tot = models.IntegerField(default=0)
    vote_average = models.FloatField(default=0)
    watchGradeNm = models.IntegerField()
    overview = models.TextField()
    repNationNm = models.ManyToManyField(RepNationNm,
                            related_name='repNationNm_movie')
    poster_path = models.CharField(max_length=100)
    backdrop_path1 = models.CharField(max_length=100)
    backdrop_path2 = models.CharField(max_length=100)
    backdrop_path3 = models.CharField(max_length=100)
    genres = models.ManyToManyField(Genre,
                            related_name='genre_movie')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_movies')

    def __str__(self):
        return f'{self.movieNm}'


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie,
                             on_delete=models.CASCADE)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    hit = models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_reviews')
    user_hit_time = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='hit_time_reviews')


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_comments')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_comments')


class Reply(models.Model):
    content = models.TextField()
    comment = models.ForeignKey(Comment,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_reply')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='dislike_reply')


class Moviehistory(models.Model):
    movie = models.ForeignKey(Movie,
                             on_delete=models.CASCADE)

class Reviewhistory(models.Model):
    review = models.ForeignKey(Review,
                             on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Userhistory, Uservisitedreview


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class CustomUserCreationForm(UserCreationForm):
    rrn = forms.IntegerField(
        help_text='11자리를 입력하세요',
        label='주민등록번호',
        )

    class Meta:
        model = get_user_model()
        fields = ['username', 'rrn', 'age', 'nickname']
        exclude = ['age',]


class UserhistoryForm(forms.ModelForm):
    class Meta:
        model = Userhistory
        fields = '__all__'
        exclude = ['user', 'movie_pk']


class UservisitedreviewForm(forms.ModelForm):
    class Meta:
        model = Uservisitedreview
        fields = '__all__'
        exclude = ['user', 'review', 'visited_time']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from movies.models import Review, Movie, Comment
from .models import Userhistory
User = get_user_model()

# Create your views here.
def signup(request):
    flag = False
    nick_flag = False
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            check_num = 0
            for idx, mul_num in enumerate((5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2)):
                check_num += user.rrn // (10 ** (idx + 1)) % 10 * mul_num
            check_num = 11 - (check_num % 11)
            nicknames = [i.nickname for i in User.objects.all()]
            if user.nickname not in nicknames:
                if check_num == user.rrn % 10:
                    if 20 - user.rrn // 100000000000 > 0:
                        user.age = 20 - user.rrn // 100000000000
                    else:
                        user.age = 120 - user.rrn // 100000000000

                    if user.rrn // 1000000 % 10 in (2, 4):
                        user.sex = '여'
                    user.save()
                    auth_login(request, user)
                    return redirect('movies:index')

                else:
                    flag = True
            else:
                nick_flag = True

    else:
        form = CustomUserCreationForm()

    context = {
        'form':form,
        'flag':flag,
        'nick_flag':nick_flag,
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    flag = False
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
        'flag':flag
    }
    return render(request,'accounts/form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@login_required
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    users_list = User.objects.all()
    users = []
    for u in users_list:
        if not u.is_superuser:
            users.append((u, Review.objects.filter(user=u).count(), Comment.objects.filter(user=u).count()))
    users.sort(reverse=True, key = lambda x : (x[1], x[2]))

    for idx, u in enumerate(users):
        if u[0] == user:
            rank = idx + 1
            break
    else:
        rank = '운영자'

    if rank == '운영자':
        tier = 'gold'
    else:
        if rank <= len(users) * 0.1:
            tier = 'gold'
        elif rank <= len(users) * 0.3:
            tier = 'silver'
        else:
            tier = 'bronze'
        rank = str(rank) + '등'

    plus_age = user.age + 1
    reviews = Review.objects.filter(user_id=pk)
    comments = Comment.objects.filter(user_id=pk)

    history = Userhistory.objects.all().filter(user=user)
    if history:
        record = {}
        for one_history in history:
            history_movie = get_object_or_404(Movie, pk=one_history.movie_pk)
            for genre in history_movie.genres.all():
                if genre in record:
                    record[genre] += 1
                else:
                    record[genre] = 1

        record_list = []
        for key in record:
            record_list.append((record[key], key))

        record_list.sort(reverse=True, key = lambda x : x[0])
        favorite_genre = record_list[0][1]
    else:
        favorite_genre = None

    context = {
        'user':user,
        'reviews':reviews,
        'comments':comments,
        'favorite_genre':favorite_genre,
        'plus_age':plus_age,
        'tier':tier,
        'rank':rank,
    }
    return render(request, 'accounts/user_detail.html', context)


def user_update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)


@login_required
def follow(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user != request.user:
        if user.followers.filter(pk=request.user.pk).exists():
            user.followers.remove(request.user)
            request.user.followings.remove(user)

        else:
            user.followers.add(request.user)
            request.user.followings.add(user)
    return redirect('accounts:detail', user.pk)

@login_required
def delete(request):
    reviews = request.user.review_set.all()
    for review in reviews:
        movie = review.movie
        movie.vote_tot -= review.rank
        movie.vote_count -= 1
        if movie.vote_count:
            movie.vote_average = round(movie.vote_tot / movie.vote_count, 1)
        else:
            movie.vote_average = 0
        movie.save()
    request.user.delete()
    return redirect('movies:index')

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if flag %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>WARNING!</strong> 유효한 주민등록번호를 입력해주세요.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

{% if nick_flag %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>WARNING!</strong> 이미 존재하는 별명입니다.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<div class='container'>
    {% if request.resolver_match.url_name == 'signup' %}
        <h2 class="modal-title" id="staticBackdropLabel">SIGN UP</h2>
    {% else %}
        <h2 class="modal-title" id="staticBackdropLabel">LOG IN</h2>
    {% endif %}
    <hr>

    <form action="" method='POST'>
        {% csrf_token %}

        {% bootstrap_form form %}

        {% if request.resolver_match.url_name == 'signup' %}
            <button type="submit" class="btn btn-primary">SIGN UP</button>
        {% else %}
            <button type="submit" class="btn btn-primary">LOG IN</button>
        {% endif %}

    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block body %}
{% if request.user == user %}
    <div class="d-flex flex-row">
      <h2 class="ml-4 mr-3" style="margin-bottom: 0px;"><i class="fas fa-house-user"></i>&nbsp;My Page</h2>
      <a class="btn btn-primary mx-1 d-flex align-items-center" href="{% url 'movies:recommend'%}" role="button">사용자 영화추천</a>
      <a class="btn btn-danger mx-1 d-flex align-items-center" href="" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-user-slash"></i>&nbsp;회원탈퇴</a>
    </div>
    <hr>
    <div class="d-flex justify-content-between ml-5">
      <div class="d-flex flex-column">
      <h4>아이디: {{ user.username }}</h4>
      <h4>닉네임: {{ user.nickname }}</h4>
      <h4>성별: {{ user.sex }}</h4>
      <h4>나이: {{ plus_age }}</h4>




{% else %}
    <h2><i class="fas fa-house-user"></i>&nbsp;{{ user.nickname }}'s Page</h2>
      {% if request.user in user.followers.all %}
          <a href="{% url 'accounts:follow' user.pk %}"><i class="fas fa-user-minus"></i>&nbsp;팔로우 취소</a>
      {% else%}
          <a href="{% url 'accounts:follow' user.pk %}"><i class="fas fa-user-plus"></i>&nbsp;팔로우</a>
      {% endif %}
<hr>
{% endif %}
<h4>최근 관심 장르:
{% if favorite_genre %}
{{ favorite_genre}}
{% else %}
관심 장르가 없습니다.
{% endif %}
</h4>

{% if request.user == user %}
    <h4>팔로잉한 유저:
    {% for fw in request.user.followings.all %}
        &nbsp;<a href="{% url 'accounts:detail' fw.pk %}">{{ fw.username }}</a>
    {% endfor %}
    </h4>
    </div>
{% endif %}
    <div class="d-flex flex-column justify-content-center mr-5">
      <h4>Follower: {{ user.followers.count }}</h4>
      <h4>Following: {{ user.followings.count }}</h4>
      <h4>게시글 수: {{ user.review_set.count }}</h4>
      <h4>댓글 수: {{ user.comment_set.count }}</h4>
      <h4>등급: {{ rank }}
      {% if tier == 'gold' %}
        <img src="{% static 'images/골드.png' %}" style="width: 28px;">
      {% elif tier == 'silver' %}
        <img src="{% static 'images/실버.png' %}" style="width: 28px;">
      {% else %}
        <img src="{% static 'images/브론즈.png' %}" style="width: 28px;">
      {% endif %}
      </h4>
    </div>
    <div></div>
    </div>


    <!--{% for history in request.user.userhistory_set.all %}-->
    <!--  <h6>{{ forloop.counter }}.{{ history.movie_pk }}</h6>-->
    <!--{% endfor %}-->

    <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">회원탈퇴</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                정말 탈퇴하시겠습니까?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                <a href="{% url 'accounts:delete' %}" class="btn btn-danger">탈퇴</a>
              </div>
            </div>
          </div>
        </div>
{% endblock %}